name: master
on:
  push:
    branches:
      - master

env:
  LATEST_TAG: "1.0"
  TESTED_TAG: "tested"
  
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # -
      #   name: Login to ACR
      #   uses: docker/login-action@v3
      #   with:
      #     registry: <registry-name>.azurecr.io
      #     username: ${{ secrets.AZURE_CLIENT_ID }}
      #     password: ${{ secrets.AZURE_CLIENT_SECRET }}
      -
        name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - 
        name: "Build and push frontend image"
        run:  |
                docker build ./frontend --tag ghcr.io/${{ env.REPO }}/frontend:${{ LATEST_TAG }}
                docker push ghcr.io/${{ env.REPO }}/frontend:${{ LATEST_TAG }}
      - 
        name: "Build and push backend image"
        run: |
              docker build ./backend --tag ghcr.io/${{ env.REPO }}/backend:${{ LATEST_TAG }}
              docker push ghcr.io/${{ env.REPO }}/backend:${{ LATEST_TAG }}
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - 
        name: "Test frontend image"
        run: |
          docker run --rm ghcr.io/${{ env.REPO }}/frontend:${{ LATEST_TAG }}
          && docker tag ghcr.io/${{ env.REPO }}/frontend:${{ LATEST_TAG }} ghcr.io/${{ env.REPO }}/backend:${{ TESTED_TAG }}
      - 
        name: "Test backend image"
        run: |
          docker run --rm ghcr.io/${{ env.REPO }}/backend:${{ LATEST_TAG }}
          && docker tag ghcr.io/${{ env.REPO }}/backend:${{ LATEST_TAG }} ghcr.io/${{ env.REPO }}/backend:${{ TESTED_TAG }}
